- name: copy node exporter service config on host 
  ansible.builtin.template: 
    src: "node_exporter.service.j2" 
    dest: "/etc/systemd/system/{{ node_exporter_service_name }}.service" 
    backup: true 
    mode: "0644" 
  notify: 
    - restart node exporter
